version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: janisuhanda
      POSTGRES_PASSWORD: janisuhanda
      POSTGRES_DB: crud-rbac-jwt
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
volumes:
  pgdata:
